server:
  port: 7001
  error:
    include-message: always

spring:
  application:
    name: product
  mongodb:
    embedded:
      version: 3.4.6
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

logging:
  level:
    root: INFO
    com.spring.cloud.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG