server:
  port: 7001
  error:
    include-message: always

spring:
  application:
    name: product
  mongodb:
    embedded:
      version: 3.4.6
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    com.spring.cloud.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG