server:
  port: 7001
  error:
    include-message: always

spring:
  mongodb:
    embedded:
      version: 5.0.0
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

logging:
  level:
    root: INFO
    com.spring.cloud.product: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG