server:
  port: 7002
  error:
    include-message: always

spring:
  mongodb:
    embedded:
      version: 3.4.6
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommend-db

logging:
  level:
    root: INFO
    com.spring.cloud: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG