server:
  port: 7000
app:
  product:
    protocol: http
    host: localhost
    port: 7001
    service: product
  recommend:
    protocol: http
    host: localhost
    port: 7002
    service: recommend
  review:
    protocol: http
    host: localhost
    port: 7003
    service: review

spring:
  application:
    name: composite
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    com.spring.cloud.composite: DEBUG