server:
  port: 8080
app:
  product:
    host: product
    port: 8080
  recommend:
    host: recommend
    port: 8080
  review:
    host: review
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/