server:
  port: 7003
  error:
    include-message: always

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user01
    password: user01
    hikari:
      initialization-fail-timeout: 60000

logging:
  level:
    root: INFO
    com.spring.cloud.review: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE